### ISSUE TITLE
I made a drawer controller but need help polishing it...

### ISSUE THREAD

**Issue by isaiah658** [minetest-mods/drawers#18]
Hey it's me again! I've been working on a Minetest subgame that is similar to modded sky block games for Minecraft. I wanted to use this mod, but there was no drawer controller which was disappointing because I wanted to have the drawers feel like a tier above chests for storage management. After a week of non stop work I have a drawer controller that is functional. I just need your help with some polish, reviewing my code for errors, and then merging it. I created a fresh fork and added my changes to it. https://github.com/isaiah658/drawers

Here are my concerns and questions:
1. I'm not sure what the best way to collaborate on this is. Should I add you as a collaborator for my fork and we work on it there before merging or should I do a pull request and we work on it at that point before merging?

2. I noticed your mod uses core. instead of minetest. for things like registering nodes. I tried searching and could not find what the difference is between the two. I've only ever used minetest. so my mod is using that instead of core. It can be changed if needed to core.

3. I think the player protection should be correct, but I'm not sure. I mostly followed how the furnace in default handled protection.

4. My code can be tidied up. If there are better ways to write things and reduce repeated code please do so. My brain is pretty much fried after getting to this point. :P

5. If you can think of ways to make the controller more efficient, let me know. The only thing that I can think of is to have the controller index all drawers that have items even if they are repeated items. For the sake of simplicity it only indexes the drawer with the most free space if the item exists in multiple drawers. Indexing more than one empty drawer won't help efficiency because if a new item is added to a empty drawer and also added to the controller around the same time, we want the controller to index the drawers again to ensure the item isn't already in a drawer before adding it to an empty one. If I'm wrong on that thinking let me know.

6. I haven't done much for bug testing other than ensure that I'm not crashing with basic usage. There are quite a few safety checks to help prevent crashes and bugs. Once we think things are finalized to be merged, I can do more extensive bug testing.

7. I only speak English so the controller doesn't have translations that other parts of the mod have.

8. I would like the controller to have support for pipeworks, but I've never worked with it. Could you make the controller have pipeworks support like the drawers have? The controller has one inventory slot called "src". Items should go in there.

If you have questions let me know. There are a lot of code comments that should help explain some of it.

**Comment by LNJ2** [comment]
1. _Just create a pull request._
2. `core` contains all functions from the minetest engine; `minetest` equals to this value (there's no difference than the name)
7. That's not a problem.
8. Just look at the docs, it's rather easy

> There are a lot of code comments that should help explain some of it.

very good
