### ISSUE TITLE
Only allow stackable items

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/drawers#2]
Unique items such as minetest_game keys looses their item data once placed in a drawer, then crashes the server/game when being used. Placing tools in a drawer resets wear levels, effectively repairs them. Placing backbacks and bags in drawers results in the same behavior I suspect, but I haven't tried it.

I realize these items coincide with what is not stackable in the regular inventory. Hence if you deny non-stackable items such as keys, backpacks and tools to be placed in drawers, the whole problem should be solved.

**Comment by LNJ2** [comment]
I thought I have added such feature already (but as it seems I haven't tested it correctly ...). I think the best solution for this is just to save the metadata (so everything is restored after taking them from the drawer).

**Comment by LNJ2** [comment]
Fixed https://github.com/minetest-mods/drawers/commit/f83177346bbc5d4c1ad0a8c2cd6a6d5a09b7780f.

**Comment by tacotexmex** [comment]
Okay, great! But you can still only store one non-stackable item in a drawer, right? :)

**Comment by LNJ2** [comment]
No, in the moment you just can't store a non-stackable item in a
drawer. (I didn't save the meta data)

**Comment by tacotexmex** [comment]
That makes sense to me. We already have itemframes for those.
