### ISSUE TITLE
Mod won't load

### ISSUE THREAD

**Issue by NathanSalapat** [minetest-mods/drawers#24]
ModError: Failed to load and run script from ~/.minetest/mods/drawers/init.lua:
~/.minetest/mods/drawers/init.lua:338: '}' expected (to close '{' at line 334) near '_mcl_blast_resistance'

Looks like you just forgot a comma in the code after the table of groups.

**Comment by LNJ2** [comment]
Thanks for reporting, please reopen if the bug persists.
