### ISSUE TITLE
Interact sounds are played globally

### ISSUE THREAD

**Issue by GreenXenith** [minetest-mods/drawers#25]
Now everyone knows where you keep your gold.

[`self.pos`](https://github.com/minetest-mods/drawers/blob/279d0ab9e8775b543034682f82b8a71cf150c9c9/lua/visual.lua#L354) should be `self.object:get_pos()`

**Comment by sofar** [comment]
Please make a PR !

**Comment by GreenXenith** [comment]
cba at the time but Ill see if I can get around to it
