### ISSUE TITLE
Bug? after breaking a drawer it left behind this?

### ISSUE THREAD

**Issue by PiMonkey04** [minetest-mods/drawers#26]
Was playing around with some drawers and broke a 4 in 1 drawer and it left behind some sort of bug, what do i do (this is on the server UnderCore)

![screenshot 139](https://user-images.githubusercontent.com/36048381/53881923-d0e58a00-400c-11e9-8bbc-28999ebeb9b3.png)

**Comment by lnjX** [comment]
This should not happen and didn't when I tested things. Thanks for reporting, but unfortunately I'm not going to investigate this.

**Comment by PiMonkey04** [comment]
ok, what can i do to get rid of it?

**Comment by PiMonkey04** [comment]
In case anyone else has this bug all you need to fix it is a Nice Admin with world worldedit that seems to fix it

**Comment by style-nine** [comment]
This sort of thing can happen with drawers placed right at the edge of a mapblock boundary. If you know where those boundaries are, you can avoid them simply by keeping space between the drawer and the boundary.

Note that you should be able to fix this bug if it occurs by placing a new drawer just behind the visual left behind by the old drawer. It may take a few tries in some cases, but that should eventually fix it.

**Comment by gpcf** [comment]
this issue still appears on linuxforks server, running the current newest git version of drawers.
