### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/drawers#3]
Let's add an open-close sound every time items are put in or taken out.

**Comment by LNJ2** [comment]
If you find some nice sounds, I'll add them! :+1:

**Comment by tacotexmex** [comment]
That's my plan 😁

**Comment by tacotexmex** [comment]
Here we go #4 !

**Comment by LNJ2** [comment]
https://github.com/minetest-mods/drawers/commit/f488fe25a6452be8d72c62b3ff260c2ad5f1c219
https://github.com/minetest-mods/drawers/commit/1f0fdf832b5a24ee80df01b0f08a0902bad8e978
