### ISSUE TITLE
Support for TechPack's tubes?

### ISSUE THREAD

**Issue by thatgraemeguy** [minetest-mods/drawers#38]
Any chance you would consider adding support for the "tubelib" tubes as found in [TechPack](https://github.com/joe7575/techpack)? They fulfil a similar function to pipeworks' tubes, but I have no clue how similar they are in terms of their implementation.

**Comment by lnjX** [comment]
Feel free to open a pull-request.

**Comment by thatgraemeguy** [comment]
Well yes..... if I was smart enough to write the code I would've.

I'll take that as a 'no' then.
