### ISSUE TITLE
phantom drawers

### ISSUE THREAD

**Issue by NathanSalapat** [minetest-mods/drawers#42]
#36 broke the removal of drawer entities, though seemingly only on the 4 drawer nodes. I found that setting the radius to 0.58 in line 200 of helpers.lua fixed it for me.

**Comment by lnjX** [comment]
Feel free to open a PR :)

**Comment by OgelGames** [comment]
This was fixed in https://github.com/minetest-mods/drawers/commit/c13238541a9cbb89e855007cf46b259fc2ab05cd.
