### ISSUE TITLE
controller cannot take items when drawer is 100% full

### ISSUE THREAD

**Issue by holgerschurig** [minetest-mods/drawers#56]
Hi,

on the Pandorabox server there a recent drawers mod installed (GIT hash "f6bca2ade23479f95d51a37053ef0cdf38f23210" with commit description " lnjX README: Add contentdb badge").

I now have a drawer controller and a drawers:aspen_wood4 (happened also with a _wood2) on top of it. No upgrade slots.

When a drawer is not at 100%, then the command

      digiline_send("controller", { name="default:tree",   count=6})
      digiline_send("controller", { name="default:leaves", count=48})

works. But when the leaves get to 100% full, then suddenly the controller won't pull any leaves out of the drawer anymore. The tree trunks will still be served.

**Comment by OgelGames** [comment]
Will be fixed by https://github.com/minetest-mods/drawers/pull/54
