### ISSUE TITLE
mineclone server crash

### ISSUE THREAD

**Issue by nonfreegithub** [minetest-mods/drawers#79]
**Drawers in mineclone 2 server causes conflict with mineclone chests then crash**

Minetest version: 5.6.1
Mineclone version: commit 02ee8b757d09c3c1fc053ef6361c5bba3a6e1efd (latest)
drawers version: commit c46e246b0444ed62445c8a45a1e8a2f9b4e0da5d

Crash log:

```
ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'mcl_core' in callback item_OnPlace(): ...t/bin/../games/MineClone2/mods/ITEMS/mcl_chests/init.lua:487: attempt to index a nil value
ERROR[Main]: stack traceback:
ERROR[Main]: 	.../.minetest/bin/../games/MineClone2/mods/ITEMS/mcl_chests/init.lua:487: in function 'on_rightclick'
ERROR[Main]: 	.../.minetest/bin/../builtin/game/item.lua:308: in function <.../.minetest/bin/../builtin/game/item.lua:301>

```

**Comment by SmallJoker** [comment]
Please reopen this issue with a backtrace that contains a line regarding `drawers`. It seems that this particular issue is only related to MCL2.
