### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by fwhcat** [minetest-mods/drawers#9]
Hi.
I have completed French Translation and would like it to be included in your mod:

https://hosted.weblate.org/projects/minetest/mod-storage-drawers/fr/

Thanks in advance.

**Comment by LNJ2** [comment]
5b971375dae96c53e23e38b167a487faff81de3f
acb5f0ab4e47ea0623ded9d0535ab42d2d89f547

**Comment by fwhcat** [comment]
Thanks for your reactivity @LNJ2 !

**Comment by LNJ2** [comment]
No problem! I thank you for your contributions! :smiley: :+1:
